# Generated by Django 6.1 on 2026-08-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_and_more'),
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', '-date'], name='attendance_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', '-date'], name='attendance_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'employee'], name='attendance_date_employee_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='attendance_employee_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('check_in__isnull', True), ('check_out__isnull', False), _connector='OR'), name='attendance_checkin_requires_checkout'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__isnull', True), ('check_in__isnull', False), _connector='OR'), name='attendance_checkout_requires_checkin'),
        ),
    ]
