# Generated by Django 6.1 on 2026-08-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/selfies/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
