# Generated by Django 6.1 on 2026-08-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_check_in_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='attendance_checkin_requires_checkout',
        ),
    ]
