# Generated by Django 6.1 on 2026-08-21 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendance_attendance_checkin_requires_checkout'),
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/selfies/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='AttendanceLocationStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters.', max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_stops', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_location_stops', to='employees.employee')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['employee', '-recorded_at'], name='location_employee_time_idx'), models.Index(fields=['attendance', '-recorded_at'], name='location_attendance_time_idx'), models.Index(fields=['recorded_at'], name='location_recorded_at_idx')],
            },
        ),
    ]
