# Generated by Django 6.1 on 2026-08-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date', 'name']},
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date', 'is_active'], name='holidays_date_active_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['holiday_type', 'date'], name='holidays_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['is_active', 'date'], name='holidays_active_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='holidays_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.CheckConstraint(condition=models.Q(('holiday_type', ''), _negated=True), name='holidays_type_not_empty'),
        ),
    ]
