# Generated by Django 6.1 on 2026-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={},
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='pay_period_end',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='pay_period_start',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='remarks',
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
