# Generated by Django 6.1 on 2026-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
        ('payroll', '0002_alter_payroll_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', '-month'], name='payroll_employee_month_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['payment_status', '-month'], name='payroll_status_month_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['-month'], name='payroll_month_idx'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('employee', 'month'), name='payroll_employee_month_unique'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gte', 0)), name='payroll_basic_salary_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('allowances__gte', 0)), name='payroll_allowances_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('deductions__gte', 0)), name='payroll_deductions_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(('net_salary__gte', 0)), name='payroll_net_salary_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_at__isnull', True), ('payment_status', 'pending')), models.Q(('paid_at__isnull', False), ('payment_status', 'paid')), _connector='OR'), name='payroll_payment_status_paid_at_consistent'),
        ),
    ]
