# Generated by Django 6.1 on 2026-08-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', '-application_date'], name='recruitment_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['department', '-application_date'], name='recruitment_dept_date_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='recruitment_email_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['job_title', '-application_date'], name='recruitment_job_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('first_name', ''), _negated=True), name='recruitment_first_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='recruitment_email_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('job_title', ''), _negated=True), name='recruitment_job_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('phone', ''), _negated=True), name='recruitment_phone_not_empty'),
        ),
    ]
