# Generated by Django 6.1 on 2026-08-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('recruitment', '0002_candidate_recruitment_status_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='candidate',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('experience_years__gte', 0)), name='recruitment_experience_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('expected_salary__isnull', True), ('expected_salary__gte', 0), _connector='OR'), name='recruitment_expected_salary_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interview_date__isnull', False), ('status', 'INTERVIEW')), models.Q(('status', 'INTERVIEW'), _negated=True), _connector='OR'), name='recruitment_interview_date_consistent'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('offer_date__isnull', False), ('status', 'SELECTED')), models.Q(('status', 'SELECTED'), _negated=True), _connector='OR'), name='recruitment_offer_date_consistent'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('joining_date__isnull', False), ('status', 'SELECTED')), models.Q(('status', 'SELECTED'), _negated=True), _connector='OR'), name='recruitment_joining_date_consistent'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('offer_date__isnull', False), ('status', 'SELECTED')), models.Q(('status', 'SELECTED'), _negated=True), _connector='OR'), name='recruitment_selected_offer_date_consistent'),
        ),
    ]
