# Generated by Django 6.1 on 2026-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('recruitment', '0003_candidate_expected_salary_candidate_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidate',
            name='recruitment_selected_offer_date_consistent',
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('joining_date__isnull', True), ('offer_date__isnull', True), ('joining_date__gte', models.F('offer_date')), _connector='OR'), name='recruitment_joining_date_after_offer'),
        ),
    ]
