# Generated by Django 6.1 on 2026-08-17 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience', '-publish_date'], name='ann_audience_date_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['department', '-publish_date'], name='ann_department_date_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-publish_date'], name='announcements_active_date_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-publish_date', '-created_at'], name='announcements_publish_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='announcements_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='announcements_message_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('expiry_date__gt', models.F('publish_date')), _connector='OR'), name='announcements_expiry_after_publish'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_audience', 'DEPARTMENT'), _negated=True), ('department__isnull', False), _connector='OR'), name='announcements_department_required'),
        ),
    ]
