# Generated by Django 6.1 on 2026-09-07 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_ann_audience_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('ANNOUNCEMENT', 'Announcement'), ('LEAVE', 'Leave'), ('ATTENDANCE', 'Attendance'), ('PAYROLL', 'Payroll'), ('PERFORMANCE', 'Performance'), ('RECRUITMENT', 'Recruitment'), ('DOCUMENT', 'Document')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recipient_read_idx'), models.Index(fields=['recipient', '-created_at'], name='notif_recipient_date_idx'), models.Index(fields=['notification_type', '-created_at'], name='notif_type_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='notifications_title_not_empty'), models.CheckConstraint(condition=models.Q(('message', ''), _negated=True), name='notifications_message_not_empty')],
            },
        ),
    ]
