# Generated by Django 6.1 on 2026-08-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('EDUCATIONAL', 'Educational Certificate'), ('EXPERIENCE', 'Experience Certificate'), ('OFFER_LETTER', 'Offer Letter'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
