# Generated by Django 6.1 on 2026-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_delete_employeedocument'),
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['employee', '-uploaded_at'], name='documents_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', '-uploaded_at'], name='documents_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='documents_uploaded_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='documents_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('document_type', ''), _negated=True), name='documents_type_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file', ''), _negated=True), name='documents_file_not_empty'),
        ),
    ]
