# Generated by Django 6.1 on 2026-09-24 08:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('department'), name='unique_designation_name_department_ci'),
        ),
    ]
