# Generated by Django 6.1 on 2026-08-12 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approval_remarks',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('earned', 'Earned Leave'), ('unpaid', 'Unpaid Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
