# Generated by Django 6.1 on 2026-08-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
        ('leave', '0002_alter_leave_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='leave_employee_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status', 'start_date'], name='leave_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['leave_type', 'start_date'], name='leave_type_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='leave',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_date_gte_start_date'),
        ),
    ]
