# Generated by Django 6.1 on 2026-08-12 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancereview',
            options={},
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='employee_comments',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='review_period_end',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='review_period_start',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='status',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_period',
            field=models.CharField(default='Annual Review', max_length=100),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='review_date',
            field=models.DateField(),
        ),
    ]
