# Generated by Django 6.1 on 2026-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_designation'),
        ('performance', '0002_alter_performancereview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancereview',
            options={'ordering': ['-review_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee', '-review_date'], name='performance_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['-review_date'], name='performance_review_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('employee', 'review_period', 'review_date'), name='performance_employee_period_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.CheckConstraint(condition=models.Q(('review_period', ''), _negated=True), name='performance_review_period_not_empty'),
        ),
    ]
